[workspace]
resolver = "2"
members = [
  "src-tauri",
  "packages/protocol-rs",
  "packages/driver-ui-host",
  "apps/postgres/ui",
  "apps/postgres/driver",
  "apps/joywatcher/ui",
  "apps/joywatcher/driver",
  "apps/joywatcher/bridge-x86",
]

[workspace.package]
edition = "2021"
license = "MIT"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[profile.dev]
opt-level = 0
