[[scan_group]]
id = "ove1w_1000ms"
driver = "local-pg"
scan_rate_ms = 1000
schema = "public"
table = "ove1w"
timestamp_column = "ptime"

[[tag]]
id = "tag-local-pg-ove1w_1000ms-w0200"
name = "w0200"
data_type = "f64"
driver = "local-pg"
scan_group = "ove1w_1000ms"
enabled = true

[tag.driver_spec]
kind = "postgres"
scanGroup = "ove1w_1000ms"
schema = "public"
table = "ove1w"
timestampColumn = "ptime"
valueColumn = "w0200"

[[tag]]
id = "tag-local-pg-ove1w_1000ms-w0201"
name = "w0201"
data_type = "f64"
driver = "local-pg"
scan_group = "ove1w_1000ms"
enabled = true

[tag.driver_spec]
kind = "postgres"
scanGroup = "ove1w_1000ms"
schema = "public"
table = "ove1w"
timestampColumn = "ptime"
valueColumn = "w0201"

[[tag]]
id = "tag-local-pg-ove1w_1000ms-w0202"
name = "w0202"
data_type = "f64"
driver = "local-pg"
scan_group = "ove1w_1000ms"
enabled = true

[tag.driver_spec]
kind = "postgres"
scanGroup = "ove1w_1000ms"
schema = "public"
table = "ove1w"
timestampColumn = "ptime"
valueColumn = "w0202"

[[tag]]
id = "tag-local-pg-ove1w_1000ms-w0203"
name = "w0203"
data_type = "f64"
driver = "local-pg"
scan_group = "ove1w_1000ms"
enabled = true

[tag.driver_spec]
kind = "postgres"
scanGroup = "ove1w_1000ms"
schema = "public"
table = "ove1w"
timestampColumn = "ptime"
valueColumn = "w0203"

[[tag]]
id = "tag-local-pg-ove1w_1000ms-w0204"
name = "w0204"
data_type = "f64"
driver = "local-pg"
scan_group = "ove1w_1000ms"
enabled = true

[tag.driver_spec]
kind = "postgres"
scanGroup = "ove1w_1000ms"
schema = "public"
table = "ove1w"
timestampColumn = "ptime"
valueColumn = "w0204"

[[tag]]
id = "tag-local-pg-ove1w_1000ms-w0205"
name = "w0205"
data_type = "f64"
driver = "local-pg"
scan_group = "ove1w_1000ms"
enabled = true

[tag.driver_spec]
kind = "postgres"
scanGroup = "ove1w_1000ms"
schema = "public"
table = "ove1w"
timestampColumn = "ptime"
valueColumn = "w0205"

[[tag]]
id = "tag-local-pg-ove1w_1000ms-w0206"
name = "w0206"
data_type = "f64"
driver = "local-pg"
scan_group = "ove1w_1000ms"
enabled = true

[tag.driver_spec]
kind = "postgres"
scanGroup = "ove1w_1000ms"
schema = "public"
table = "ove1w"
timestampColumn = "ptime"
valueColumn = "w0206"

[[tag]]
id = "tag-local-pg-ove1w_1000ms-w0207"
name = "w0207"
data_type = "f64"
driver = "local-pg"
scan_group = "ove1w_1000ms"
enabled = true

[tag.driver_spec]
kind = "postgres"
scanGroup = "ove1w_1000ms"
schema = "public"
table = "ove1w"
timestampColumn = "ptime"
valueColumn = "w0207"

[[tag]]
id = "tag-local-pg-ove1w_1000ms-w0208"
name = "w0208"
data_type = "f64"
driver = "local-pg"
scan_group = "ove1w_1000ms"
enabled = true

[tag.driver_spec]
kind = "postgres"
scanGroup = "ove1w_1000ms"
schema = "public"
table = "ove1w"
timestampColumn = "ptime"
valueColumn = "w0208"

[[tag]]
id = "tag-local-pg-ove1w_1000ms-w0210"
name = "w0210"
data_type = "f64"
driver = "local-pg"
scan_group = "ove1w_1000ms"
enabled = true

[tag.driver_spec]
kind = "postgres"
scanGroup = "ove1w_1000ms"
schema = "public"
table = "ove1w"
timestampColumn = "ptime"
valueColumn = "w0210"
