[[scan_group]]
id = "gourp1"
driver = "pg_main"
scan_rate_ms = 1000
schema = "public"
table = "bte1w"
timestamp_column = "ptime"

[[tag]]
id = "tag-pg_main-gourp1-w0400"
name = "w0400"
data_type = "f64"
driver = "pg_main"
scan_group = "gourp1"
enabled = true

[tag.driver_spec]
kind = "postgres"
scanGroup = "gourp1"
schema = "public"
table = "bte1w"
timestampColumn = "ptime"
valueColumn = "w0400"

[[tag]]
id = "tag-pg_main-gourp1-w0401"
name = "w0401"
data_type = "f64"
driver = "pg_main"
scan_group = "gourp1"
enabled = true

[tag.driver_spec]
kind = "postgres"
scanGroup = "gourp1"
schema = "public"
table = "bte1w"
timestampColumn = "ptime"
valueColumn = "w0401"

[[tag]]
id = "tag-pg_main-gourp1-w0402"
name = "w0402"
data_type = "f64"
driver = "pg_main"
scan_group = "gourp1"
enabled = true

[tag.driver_spec]
kind = "postgres"
scanGroup = "gourp1"
schema = "public"
table = "bte1w"
timestampColumn = "ptime"
valueColumn = "w0402"

[[tag]]
id = "tag-pg_main-gourp1-w0403"
name = "w0403"
data_type = "f64"
driver = "pg_main"
scan_group = "gourp1"
enabled = true

[tag.driver_spec]
kind = "postgres"
scanGroup = "gourp1"
schema = "public"
table = "bte1w"
timestampColumn = "ptime"
valueColumn = "w0403"
